name: Python CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_IMAGE: sirisha849/python-ci-app:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Stage 1: Checkout Code & Setup
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Stage 2: Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Stage 3: Static Code Analysis (Linting)
      - name: Lint code with Flake8
        run: |
          flake8 .

      # Stage 4: Security Scanning
      - name: Bandit security scan
        run: |
          bandit -r .

      # Stage 5: Unit Test & Coverage
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Stage 6: Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .

      # Stage 7: Scan Docker Image for vulnerabilities
      - name: Scan Docker image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}

      # Stage 8: Push to Artifact Repository (Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_IMAGE }}
